apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-rc
  labels:
    app: myapp
    type: front-end
    tier: front-end
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: front-end
  template:
    metadata:
      labels:
        app: myapp
        type: front-end
        tier: front-end
    spec:
      containers:
        - name: nginx-container
          image: nginx
