apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-rc
  labels:
    app: myapp
    type: front-end
spec:  # creates a ReplicaSet
  replicas: 6  # might differ from existing pods
  selector:
    matchLabels:
      type: front-end
  template:  # pod template for ReplicaSet
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        type: front-end
    spec:
      containers:
        - name: nginx-container
          image: nginx
